#===================================== 基本配置 =====================================#
# 服务端口号
server:
    port: 8083

#===================================== RabbitMQ 配置 =====================================#
# 配置 RabbitMQ 服务
spring:
    rabbitmq:
        username: admin
        password: admin
        virtual-host: /
        host: 192.168.247.191
        port: 5672
